// Code generated by scripts/gen_store_forward.go; DO NOT EDIT.
package store

import "database/sql"

func (s *MySQL) Close() error {
	if s == nil {
		return nil
	}
	if s.json != nil {
		return s.json.Close()
	}
	if s.sql != nil {
		return s.sql.Close()
	}
	return nil
}

func (s *MySQL) Ping() error {
	if s == nil {
		return sql.ErrConnDone
	}
	if s.json != nil {
		return s.json.Ping()
	}
	if s.sql != nil {
		return s.sql.Ping()
	}
	return sql.ErrConnDone
}

func (s *MySQL) DB() *sql.DB {
	if s == nil || s.sql == nil {
		return nil
	}
	return s.sql.DB()
}

func (s *MySQL) AddAutoFightTimes(uid int64, delta int) (int, error) {
	if s.json != nil {
		return s.json.AddAutoFightTimes(uid, delta)
	}
	return s.sql.AddAutoFightTimes(uid, delta)
}

func (s *MySQL) AddBlacklist(uid, blackID int64) error {
	if s.json != nil {
		return s.json.AddBlacklist(uid, blackID)
	}
	return s.sql.AddBlacklist(uid, blackID)
}

func (s *MySQL) AddCoins(uid int64, delta int) error {
	if s.json != nil {
		return s.json.AddCoins(uid, delta)
	}
	return s.sql.AddCoins(uid, delta)
}

func (s *MySQL) AddEnergyTimes(uid int64, delta int) (int, error) {
	if s.json != nil {
		return s.json.AddEnergyTimes(uid, delta)
	}
	return s.sql.AddEnergyTimes(uid, delta)
}

func (s *MySQL) AddExpPool(uid int64, delta int) (int, error) {
	if s.json != nil {
		return s.json.AddExpPool(uid, delta)
	}
	return s.sql.AddExpPool(uid, delta)
}

func (s *MySQL) AddFriend(uid, friendID int64) error {
	if s.json != nil {
		return s.json.AddFriend(uid, friendID)
	}
	return s.sql.AddFriend(uid, friendID)
}

func (s *MySQL) AddGold(uid int64, delta int) error {
	if s.json != nil {
		return s.json.AddGold(uid, delta)
	}
	return s.sql.AddGold(uid, delta)
}

func (s *MySQL) AddGoldPromoCount(uid int64) (int, error) {
	if s.json != nil {
		return s.json.AddGoldPromoCount(uid)
	}
	return s.sql.AddGoldPromoCount(uid)
}

func (s *MySQL) AddGoldWithLedger(uid int64, delta int, reason, ref string) (balance int, err error) {
	if s.json != nil {
		return s.json.AddGoldWithLedger(uid, delta, reason, ref)
	}
	return s.sql.AddGoldWithLedger(uid, delta, reason, ref)
}

func (s *MySQL) AddItem(uid int64, itemID, delta int) error {
	if s.json != nil {
		return s.json.AddItem(uid, itemID, delta)
	}
	return s.sql.AddItem(uid, itemID, delta)
}

func (s *MySQL) AddLearnTimes(uid int64, delta int) (int, error) {
	if s.json != nil {
		return s.json.AddLearnTimes(uid, delta)
	}
	return s.sql.AddLearnTimes(uid, delta)
}

func (s *MySQL) AddThreeTimes(uid int64, delta int) (int, error) {
	if s.json != nil {
		return s.json.AddThreeTimes(uid, delta)
	}
	return s.sql.AddThreeTimes(uid, delta)
}

func (s *MySQL) AddTwoTimes(uid int64, delta int) (int, error) {
	if s.json != nil {
		return s.json.AddTwoTimes(uid, delta)
	}
	return s.sql.AddTwoTimes(uid, delta)
}

func (s *MySQL) ClaimRecruitSlot(uid int64, slot uint32) (already bool, mask uint32, err error) {
	if s.json != nil {
		return s.json.ClaimRecruitSlot(uid, slot)
	}
	return s.sql.ClaimRecruitSlot(uid, slot)
}

func (s *MySQL) ClearHatchState(uid int64) error {
	if s.json != nil {
		return s.json.ClearHatchState(uid)
	}
	return s.sql.ClearHatchState(uid)
}

func (s *MySQL) ConsumeAutoFightTimes(uid int64, n int) (ok bool, left int, err error) {
	if s.json != nil {
		return s.json.ConsumeAutoFightTimes(uid, n)
	}
	return s.sql.ConsumeAutoFightTimes(uid, n)
}

func (s *MySQL) ConsumeItem(uid int64, itemID, amount int) error {
	if s.json != nil {
		return s.json.ConsumeItem(uid, itemID, amount)
	}
	return s.sql.ConsumeItem(uid, itemID, amount)
}

func (s *MySQL) ConsumeLearnTimes(uid int64, n int) (ok bool, left int, err error) {
	if s.json != nil {
		return s.json.ConsumeLearnTimes(uid, n)
	}
	return s.sql.ConsumeLearnTimes(uid, n)
}

func (s *MySQL) ConsumeThreeTimes(uid int64, n int) (ok bool, left int, err error) {
	if s.json != nil {
		return s.json.ConsumeThreeTimes(uid, n)
	}
	return s.sql.ConsumeThreeTimes(uid, n)
}

func (s *MySQL) ConsumeTwoTimes(uid int64, n int) (ok bool, left int, err error) {
	if s.json != nil {
		return s.json.ConsumeTwoTimes(uid, n)
	}
	return s.sql.ConsumeTwoTimes(uid, n)
}

func (s *MySQL) CountBagPets(uid int64) (int, error) {
	if s.json != nil {
		return s.json.CountBagPets(uid)
	}
	return s.sql.CountBagPets(uid)
}

func (s *MySQL) CountRoweiPets(uid int64) (int, error) {
	if s.json != nil {
		return s.json.CountRoweiPets(uid)
	}
	return s.sql.CountRoweiPets(uid)
}

func (s *MySQL) CountUnreadMails(uid int64) (int, error) {
	if s.json != nil {
		return s.json.CountUnreadMails(uid)
	}
	return s.sql.CountUnreadMails(uid)
}

func (s *MySQL) CreateUser(email, passwordMD5 string) (*User, error) {
	if s.json != nil {
		return s.json.CreateUser(email, passwordMD5)
	}
	return s.sql.CreateUser(email, passwordMD5)
}

func (s *MySQL) DeleteAllMails(uid int64) error {
	if s.json != nil {
		return s.json.DeleteAllMails(uid)
	}
	return s.sql.DeleteAllMails(uid)
}

func (s *MySQL) DeleteMails(uid int64, ids []int64) error {
	if s.json != nil {
		return s.json.DeleteMails(uid, ids)
	}
	return s.sql.DeleteMails(uid, ids)
}

func (s *MySQL) DeletePet(uid, catchTime int64) error {
	if s.json != nil {
		return s.json.DeletePet(uid, catchTime)
	}
	return s.sql.DeletePet(uid, catchTime)
}

func (s *MySQL) DeleteSoulBead(uid int64, obtainTime uint32) error {
	if s.json != nil {
		return s.json.DeleteSoulBead(uid, obtainTime)
	}
	return s.sql.DeleteSoulBead(uid, obtainTime)
}

func (s *MySQL) DeleteTask(uid int64, taskID int) error {
	if s.json != nil {
		return s.json.DeleteTask(uid, taskID)
	}
	return s.sql.DeleteTask(uid, taskID)
}

func (s *MySQL) EncodeLoginTaskList(uid int64, size int) ([]byte, error) {
	if s.json != nil {
		return s.json.EncodeLoginTaskList(uid, size)
	}
	return s.sql.EncodeLoginTaskList(uid, size)
}

func (s *MySQL) EndPetExe(uid, catchTime int64) (*Pet, error) {
	if s.json != nil {
		return s.json.EndPetExe(uid, catchTime)
	}
	return s.sql.EndPetExe(uid, catchTime)
}

func (s *MySQL) EnsureEquip(uid int64, itemID, level int) error {
	if s.json != nil {
		return s.json.EnsureEquip(uid, itemID, level)
	}
	return s.sql.EnsureEquip(uid, itemID, level)
}

func (s *MySQL) FindByEmail(email string) (*User, error) {
	if s.json != nil {
		return s.json.FindByEmail(email)
	}
	return s.sql.FindByEmail(email)
}

func (s *MySQL) FindByUserID(uid int64) (*User, error) {
	if s.json != nil {
		return s.json.FindByUserID(uid)
	}
	return s.sql.FindByUserID(uid)
}

func (s *MySQL) GetAchieveBranchState(uid int64, branchID int) (value, status int, err error) {
	if s.json != nil {
		return s.json.GetAchieveBranchState(uid, branchID)
	}
	return s.sql.GetAchieveBranchState(uid, branchID)
}

func (s *MySQL) GetBoostTimes(uid int64) (BoostTimes, error) {
	if s.json != nil {
		return s.json.GetBoostTimes(uid)
	}
	return s.sql.GetBoostTimes(uid)
}

func (s *MySQL) GetBreedState(uid int64) (BreedState, error) {
	if s.json != nil {
		return s.json.GetBreedState(uid)
	}
	return s.sql.GetBreedState(uid)
}

func (s *MySQL) GetCoins(uid int64) (int, error) {
	if s.json != nil {
		return s.json.GetCoins(uid)
	}
	return s.sql.GetCoins(uid)
}

func (s *MySQL) GetEquipLevel(uid int64, itemID int) (int, error) {
	if s.json != nil {
		return s.json.GetEquipLevel(uid, itemID)
	}
	return s.sql.GetEquipLevel(uid, itemID)
}

func (s *MySQL) GetExpPool(uid int64) (int, error) {
	if s.json != nil {
		return s.json.GetExpPool(uid)
	}
	return s.sql.GetExpPool(uid)
}

func (s *MySQL) GetGaiyaEffect(uid int64) (defID, mask int, err error) {
	if s.json != nil {
		return s.json.GetGaiyaEffect(uid)
	}
	return s.sql.GetGaiyaEffect(uid)
}

func (s *MySQL) GetGold(uid int64) (int, error) {
	if s.json != nil {
		return s.json.GetGold(uid)
	}
	return s.sql.GetGold(uid)
}

func (s *MySQL) GetGoldPromoCount(uid int64) (int, error) {
	if s.json != nil {
		return s.json.GetGoldPromoCount(uid)
	}
	return s.sql.GetGoldPromoCount(uid)
}

func (s *MySQL) GetHatchState(uid int64) (HatchState, error) {
	if s.json != nil {
		return s.json.GetHatchState(uid)
	}
	return s.sql.GetHatchState(uid)
}

func (s *MySQL) GetItemCount(uid int64, itemID int) (int, error) {
	if s.json != nil {
		return s.json.GetItemCount(uid, itemID)
	}
	return s.sql.GetItemCount(uid, itemID)
}

func (s *MySQL) GetMail(uid, mailID int64) (*Mail, error) {
	if s.json != nil {
		return s.json.GetMail(uid, mailID)
	}
	return s.sql.GetMail(uid, mailID)
}

func (s *MySQL) GetNono(uid int64) (*Nono, error) {
	if s.json != nil {
		return s.json.GetNono(uid)
	}
	return s.sql.GetNono(uid)
}

func (s *MySQL) GetOrInitNono(uid int64) (*Nono, error) {
	if s.json != nil {
		return s.json.GetOrInitNono(uid)
	}
	return s.sql.GetOrInitNono(uid)
}

func (s *MySQL) GetPetByCatchTime(uid, catchTime int64) (*Pet, error) {
	if s.json != nil {
		return s.json.GetPetByCatchTime(uid, catchTime)
	}
	return s.sql.GetPetByCatchTime(uid, catchTime)
}

func (s *MySQL) GetProgress(uid int64) (UserProgress, error) {
	if s.json != nil {
		return s.json.GetProgress(uid)
	}
	return s.sql.GetProgress(uid)
}

func (s *MySQL) GetRecruitClaimMask(uid int64) (uint32, error) {
	if s.json != nil {
		return s.json.GetRecruitClaimMask(uid)
	}
	return s.sql.GetRecruitClaimMask(uid)
}

func (s *MySQL) GetSoulBead(uid int64, obtainTime uint32) (*SoulBead, error) {
	if s.json != nil {
		return s.json.GetSoulBead(uid, obtainTime)
	}
	return s.sql.GetSoulBead(uid, obtainTime)
}

func (s *MySQL) GetTask(uid int64, taskID int) (*Task, error) {
	if s.json != nil {
		return s.json.GetTask(uid, taskID)
	}
	return s.sql.GetTask(uid, taskID)
}

func (s *MySQL) GrantPet(uid int64, petID int, name string, level, dv, nature int, skills []int) (catchTime int64, err error) {
	if s.json != nil {
		return s.json.GrantPet(uid, petID, name, level, dv, nature, skills)
	}
	return s.sql.GrantPet(uid, petID, name, level, dv, nature, skills)
}

func (s *MySQL) GrantPetsBatch(uid int64, pets []Pet) (granted int, firstCatch int64, err error) {
	if s.json != nil {
		return s.json.GrantPetsBatch(uid, pets)
	}
	return s.sql.GrantPetsBatch(uid, pets)
}

func (s *MySQL) GrantTitle(uid int64, titleID int) error {
	if s.json != nil {
		return s.json.GrantTitle(uid, titleID)
	}
	return s.sql.GrantTitle(uid, titleID)
}

func (s *MySQL) HasDefeatedSPT(uid int64, bossKey int) (bool, error) {
	if s.json != nil {
		return s.json.HasDefeatedSPT(uid, bossKey)
	}
	return s.sql.HasDefeatedSPT(uid, bossKey)
}

func (s *MySQL) InsertGMAudit(admin, action string, targetUID int64, detail any) (int64, error) {
	if s.json != nil {
		return s.json.InsertGMAudit(admin, action, targetUID, detail)
	}
	return s.sql.InsertGMAudit(admin, action, targetUID, detail)
}

func (s *MySQL) InsertMail(uid int64, template int, fromID int64, fromNick, content string) (int64, error) {
	if s.json != nil {
		return s.json.InsertMail(uid, template, fromID, fromNick, content)
	}
	return s.sql.InsertMail(uid, template, fromID, fromNick, content)
}

func (s *MySQL) InsertMailWithReward(uid int64, template int, fromID int64, fromNick, content string, reward MailReward) (int64, error) {
	if s.json != nil {
		return s.json.InsertMailWithReward(uid, template, fromID, fromNick, content, reward)
	}
	return s.sql.InsertMailWithReward(uid, template, fromID, fromNick, content, reward)
}

func (s *MySQL) IsFriend(uid, friendID int64) (bool, error) {
	if s.json != nil {
		return s.json.IsFriend(uid, friendID)
	}
	return s.sql.IsFriend(uid, friendID)
}

func (s *MySQL) IsPetCollectClaimed(uid int64, period int) (bool, error) {
	if s.json != nil {
		return s.json.IsPetCollectClaimed(uid, period)
	}
	return s.sql.IsPetCollectClaimed(uid, period)
}

func (s *MySQL) ListAchieveRules(uid int64) ([]AchieveRuleRow, error) {
	if s.json != nil {
		return s.json.ListAchieveRules(uid)
	}
	return s.sql.ListAchieveRules(uid)
}

func (s *MySQL) ListAchieveRulesOfBranch(uid int64, branchID int) ([]AchieveRuleRow, error) {
	if s.json != nil {
		return s.json.ListAchieveRulesOfBranch(uid, branchID)
	}
	return s.sql.ListAchieveRulesOfBranch(uid, branchID)
}

func (s *MySQL) ListAllItems(uid int64) ([]Item, error) {
	if s.json != nil {
		return s.json.ListAllItems(uid)
	}
	return s.sql.ListAllItems(uid)
}

func (s *MySQL) ListBagPets(uid int64) ([]Pet, error) {
	if s.json != nil {
		return s.json.ListBagPets(uid)
	}
	return s.sql.ListBagPets(uid)
}

func (s *MySQL) ListBlacklist(uid int64) ([]BlackEntry, error) {
	if s.json != nil {
		return s.json.ListBlacklist(uid)
	}
	return s.sql.ListBlacklist(uid)
}

func (s *MySQL) ListDefeatedSPTKeys(uid int64) ([]int, error) {
	if s.json != nil {
		return s.json.ListDefeatedSPTKeys(uid)
	}
	return s.sql.ListDefeatedSPTKeys(uid)
}

func (s *MySQL) ListEquipLevels(uid int64) (map[int]int, error) {
	if s.json != nil {
		return s.json.ListEquipLevels(uid)
	}
	return s.sql.ListEquipLevels(uid)
}

func (s *MySQL) ListExePets(uid int64) ([]Pet, error) {
	if s.json != nil {
		return s.json.ListExePets(uid)
	}
	return s.sql.ListExePets(uid)
}

func (s *MySQL) ListFitmentItems(uid int64) ([]Item, error) {
	if s.json != nil {
		return s.json.ListFitmentItems(uid)
	}
	return s.sql.ListFitmentItems(uid)
}

func (s *MySQL) ListFitments(uid int64) ([]Fitment, error) {
	if s.json != nil {
		return s.json.ListFitments(uid)
	}
	return s.sql.ListFitments(uid)
}

func (s *MySQL) ListFriends(uid int64) ([]FriendEntry, error) {
	if s.json != nil {
		return s.json.ListFriends(uid)
	}
	return s.sql.ListFriends(uid)
}

func (s *MySQL) ListGMAudit(limit int) ([]map[string]any, error) {
	if s.json != nil {
		return s.json.ListGMAudit(limit)
	}
	return s.sql.ListGMAudit(limit)
}

func (s *MySQL) ListItemsInRange(uid int64, lo, hi, extra int) ([]Item, error) {
	if s.json != nil {
		return s.json.ListItemsInRange(uid, lo, hi, extra)
	}
	return s.sql.ListItemsInRange(uid, lo, hi, extra)
}

func (s *MySQL) ListMails(uid int64, start int) (total int, mails []Mail, err error) {
	if s.json != nil {
		return s.json.ListMails(uid, start)
	}
	return s.sql.ListMails(uid, start)
}

func (s *MySQL) ListRoweiPets(uid int64) ([]Pet, error) {
	if s.json != nil {
		return s.json.ListRoweiPets(uid)
	}
	return s.sql.ListRoweiPets(uid)
}

func (s *MySQL) ListSoulBeads(uid int64) ([]SoulBead, error) {
	if s.json != nil {
		return s.json.ListSoulBeads(uid)
	}
	return s.sql.ListSoulBeads(uid)
}

func (s *MySQL) ListStoragePets(uid int64) ([]Pet, error) {
	if s.json != nil {
		return s.json.ListStoragePets(uid)
	}
	return s.sql.ListStoragePets(uid)
}

func (s *MySQL) ListTaskStatuses(uid int64) (map[int]int, error) {
	if s.json != nil {
		return s.json.ListTaskStatuses(uid)
	}
	return s.sql.ListTaskStatuses(uid)
}

func (s *MySQL) ListTitles(uid int64) ([]int, error) {
	if s.json != nil {
		return s.json.ListTitles(uid)
	}
	return s.sql.ListTitles(uid)
}

func (s *MySQL) ListWornClothes(uid int64) ([]WornCloth, error) {
	if s.json != nil {
		return s.json.ListWornClothes(uid)
	}
	return s.sql.ListWornClothes(uid)
}

func (s *MySQL) MarkDefeatedSPT(uid int64, bossKey int) error {
	if s.json != nil {
		return s.json.MarkDefeatedSPT(uid, bossKey)
	}
	return s.sql.MarkDefeatedSPT(uid, bossKey)
}

func (s *MySQL) MarkMailsRead(uid int64, ids []int64) error {
	if s.json != nil {
		return s.json.MarkMailsRead(uid, ids)
	}
	return s.sql.MarkMailsRead(uid, ids)
}

func (s *MySQL) MarkMailsReadAndClaim(uid int64, ids []int64) ([]Mail, error) {
	if s.json != nil {
		return s.json.MarkMailsReadAndClaim(uid, ids)
	}
	return s.sql.MarkMailsReadAndClaim(uid, ids)
}

func (s *MySQL) MarkPetCollectClaimed(uid int64, period int) error {
	if s.json != nil {
		return s.json.MarkPetCollectClaimed(uid, period)
	}
	return s.sql.MarkPetCollectClaimed(uid, period)
}

func (s *MySQL) MovePetToBag(uid, catchTime int64) (*Pet, bool, error) {
	if s.json != nil {
		return s.json.MovePetToBag(uid, catchTime)
	}
	return s.sql.MovePetToBag(uid, catchTime)
}

func (s *MySQL) MovePetToExe(uid, catchTime int64, course int, startUnix int64) error {
	if s.json != nil {
		return s.json.MovePetToExe(uid, catchTime, course, startUnix)
	}
	return s.sql.MovePetToExe(uid, catchTime, course, startUnix)
}

func (s *MySQL) MovePetToRowei(uid, catchTime int64) error {
	if s.json != nil {
		return s.json.MovePetToRowei(uid, catchTime)
	}
	return s.sql.MovePetToRowei(uid, catchTime)
}

func (s *MySQL) MovePetToStorage(uid, catchTime int64) (firstCatch int64, ok bool, err error) {
	if s.json != nil {
		return s.json.MovePetToStorage(uid, catchTime)
	}
	return s.sql.MovePetToStorage(uid, catchTime)
}

func (s *MySQL) NormalizeBagOverflow(uid int64) (int, error) {
	if s.json != nil {
		return s.json.NormalizeBagOverflow(uid)
	}
	return s.sql.NormalizeBagOverflow(uid)
}

func (s *MySQL) RemoveBlacklist(uid, blackID int64) error {
	if s.json != nil {
		return s.json.RemoveBlacklist(uid, blackID)
	}
	return s.sql.RemoveBlacklist(uid, blackID)
}

func (s *MySQL) RemoveFriend(uid, friendID int64) error {
	if s.json != nil {
		return s.json.RemoveFriend(uid, friendID)
	}
	return s.sql.RemoveFriend(uid, friendID)
}

func (s *MySQL) ReplaceFitments(uid int64, list []Fitment) error {
	if s.json != nil {
		return s.json.ReplaceFitments(uid, list)
	}
	return s.sql.ReplaceFitments(uid, list)
}

func (s *MySQL) RetrievePetFromRowei(uid, catchTime int64) error {
	if s.json != nil {
		return s.json.RetrievePetFromRowei(uid, catchTime)
	}
	return s.sql.RetrievePetFromRowei(uid, catchTime)
}

func (s *MySQL) SaveUser(u *User) error {
	if s.json != nil {
		return s.json.SaveUser(u)
	}
	return s.sql.SaveUser(u)
}

func (s *MySQL) SearchUsers(q string, limit int) ([]UserBrief, error) {
	if s.json != nil {
		return s.json.SearchUsers(q, limit)
	}
	return s.sql.SearchUsers(q, limit)
}

func (s *MySQL) SetAchieveBranchState(uid int64, branchID, value, status int) error {
	if s.json != nil {
		return s.json.SetAchieveBranchState(uid, branchID, value, status)
	}
	return s.sql.SetAchieveBranchState(uid, branchID, value, status)
}

func (s *MySQL) SetAutoFight(uid int64, n int) error {
	if s.json != nil {
		return s.json.SetAutoFight(uid, n)
	}
	return s.sql.SetAutoFight(uid, n)
}

func (s *MySQL) SetAutoFightTimes(uid int64, n int) error {
	if s.json != nil {
		return s.json.SetAutoFightTimes(uid, n)
	}
	return s.sql.SetAutoFightTimes(uid, n)
}

func (s *MySQL) SetBraveProgress(uid int64, cur int) error {
	if s.json != nil {
		return s.json.SetBraveProgress(uid, cur)
	}
	return s.sql.SetBraveProgress(uid, cur)
}

func (s *MySQL) SetBreedState(uid int64, st BreedState) error {
	if s.json != nil {
		return s.json.SetBreedState(uid, st)
	}
	return s.sql.SetBreedState(uid, st)
}

func (s *MySQL) GetRoomPets(uid int64) (RoomPets, error) {
	if s.json != nil {
		return s.json.GetRoomPets(uid)
	}
	return s.sql.GetRoomPets(uid)
}

func (s *MySQL) SetRoomPets(uid int64, list RoomPets) error {
	if s.json != nil {
		return s.json.SetRoomPets(uid, list)
	}
	return s.sql.SetRoomPets(uid, list)
}

func (s *MySQL) GetNonoVipSign(uid int64) (NonoVipSignState, error) {
	if s.json != nil {
		return s.json.GetNonoVipSign(uid)
	}
	return s.sql.GetNonoVipSign(uid)
}

func (s *MySQL) SetNonoVipSign(uid int64, st NonoVipSignState) error {
	if s.json != nil {
		return s.json.SetNonoVipSign(uid, st)
	}
	return s.sql.SetNonoVipSign(uid, st)
}

func (s *MySQL) GetUserOps(uid int64) (UserOpsState, error) {
	if s.json != nil {
		return s.json.GetUserOps(uid)
	}
	return s.sql.GetUserOps(uid)
}

func (s *MySQL) SetUserOps(uid int64, st UserOpsState) error {
	if s.json != nil {
		return s.json.SetUserOps(uid, st)
	}
	return s.sql.SetUserOps(uid, st)
}

func (s *MySQL) ListTopWarRanks(limit int) ([]TopWarRankEntry, error) {
	if s.json != nil {
		return s.json.ListTopWarRanks(limit)
	}
	return s.sql.ListTopWarRanks(limit)
}

func (s *MySQL) GetLeiyiTrain(uid int64) (LeiyiTrainProgress, error) {
	if s.json != nil {
		return s.json.GetLeiyiTrain(uid)
	}
	return s.sql.GetLeiyiTrain(uid)
}

func (s *MySQL) SetLeiyiTrain(uid int64, st LeiyiTrainProgress) error {
	if s.json != nil {
		return s.json.SetLeiyiTrain(uid, st)
	}
	return s.sql.SetLeiyiTrain(uid, st)
}

func (s *MySQL) SetPetTrainBonus(uid, catchTime int64, bonus [6]int) error {
	if s.json != nil {
		return s.json.SetPetTrainBonus(uid, catchTime, bonus)
	}
	return s.sql.SetPetTrainBonus(uid, catchTime, bonus)
}

func (s *MySQL) SetPetGMStats(uid, catchTime int64, stats [6]int) error {
	if s.json != nil {
		return s.json.SetPetGMStats(uid, catchTime, stats)
	}
	return s.sql.SetPetGMStats(uid, catchTime, stats)
}

func (s *MySQL) ClearPetGMStats(uid, catchTime int64) error {
	if s.json != nil {
		return s.json.ClearPetGMStats(uid, catchTime)
	}
	return s.sql.ClearPetGMStats(uid, catchTime)
}

func (s *MySQL) SetPetLearnedSkillBank(uid, catchTime int64, skills []int) error {
	if s.json != nil {
		return s.json.SetPetLearnedSkillBank(uid, catchTime, skills)
	}
	return s.sql.SetPetLearnedSkillBank(uid, catchTime, skills)
}

func (s *MySQL) SetDefaultPet(uid, catchTime int64) error {
	if s.json != nil {
		return s.json.SetDefaultPet(uid, catchTime)
	}
	return s.sql.SetDefaultPet(uid, catchTime)
}

func (s *MySQL) SetEnergyTimes(uid int64, n int) error {
	if s.json != nil {
		return s.json.SetEnergyTimes(uid, n)
	}
	return s.sql.SetEnergyTimes(uid, n)
}

func (s *MySQL) SetEquipLevel(uid int64, itemID, level int) error {
	if s.json != nil {
		return s.json.SetEquipLevel(uid, itemID, level)
	}
	return s.sql.SetEquipLevel(uid, itemID, level)
}

func (s *MySQL) SetExpPool(uid int64, value int) error {
	if s.json != nil {
		return s.json.SetExpPool(uid, value)
	}
	return s.sql.SetExpPool(uid, value)
}

func (s *MySQL) SetFreshProgress(uid int64, cur int) error {
	if s.json != nil {
		return s.json.SetFreshProgress(uid, cur)
	}
	return s.sql.SetFreshProgress(uid, cur)
}

func (s *MySQL) SetGaiyaEffect(uid int64, defID, mask int) error {
	if s.json != nil {
		return s.json.SetGaiyaEffect(uid, defID, mask)
	}
	return s.sql.SetGaiyaEffect(uid, defID, mask)
}

func (s *MySQL) SetHatchState(uid int64, h HatchState) error {
	if s.json != nil {
		return s.json.SetHatchState(uid, h)
	}
	return s.sql.SetHatchState(uid, h)
}

func (s *MySQL) SetLearnTimes(uid int64, n int) error {
	if s.json != nil {
		return s.json.SetLearnTimes(uid, n)
	}
	return s.sql.SetLearnTimes(uid, n)
}

func (s *MySQL) SetPetBagFlag(uid, catchTime int64, inBag bool, bagPos int) error {
	if s.json != nil {
		return s.json.SetPetBagFlag(uid, catchTime, inBag, bagPos)
	}
	return s.sql.SetPetBagFlag(uid, catchTime, inBag, bagPos)
}

func (s *MySQL) SetPetCurrentHP(uid, catchTime int64, hp int) error {
	if s.json != nil {
		return s.json.SetPetCurrentHP(uid, catchTime, hp)
	}
	return s.sql.SetPetCurrentHP(uid, catchTime, hp)
}

func (s *MySQL) SetPetEV(uid, catchTime int64, ev [6]int) error {
	if s.json != nil {
		return s.json.SetPetEV(uid, catchTime, ev)
	}
	return s.sql.SetPetEV(uid, catchTime, ev)
}

func (s *MySQL) SetPetElite(uid, catchTime int64, elite bool) error {
	if s.json != nil {
		return s.json.SetPetElite(uid, catchTime, elite)
	}
	return s.sql.SetPetElite(uid, catchTime, elite)
}

func (s *MySQL) SetPetEnergyBall(uid, catchTime int64, itemID, leftCount, effectID int) error {
	if s.json != nil {
		return s.json.SetPetEnergyBall(uid, catchTime, itemID, leftCount, effectID)
	}
	return s.sql.SetPetEnergyBall(uid, catchTime, itemID, leftCount, effectID)
}

func (s *MySQL) SetPetExe(uid, catchTime int64, start int64, course int) error {
	if s.json != nil {
		return s.json.SetPetExe(uid, catchTime, start, course)
	}
	return s.sql.SetPetExe(uid, catchTime, start, course)
}

func (s *MySQL) SetPetFormDisplay(uid, catchTime int64, formLocked, displayFormID, lockedDisplayFormID int) error {
	if s.json != nil {
		return s.json.SetPetFormDisplay(uid, catchTime, formLocked, displayFormID, lockedDisplayFormID)
	}
	return s.sql.SetPetFormDisplay(uid, catchTime, formLocked, displayFormID, lockedDisplayFormID)
}

func (s *MySQL) SetPetTrait(uid, catchTime int64, trait int) error {
	if s.json != nil {
		return s.json.SetPetTrait(uid, catchTime, trait)
	}
	return s.sql.SetPetTrait(uid, catchTime, trait)
}

func (s *MySQL) SetRecruitClaimMask(uid int64, mask uint32) error {
	if s.json != nil {
		return s.json.SetRecruitClaimMask(uid, mask)
	}
	return s.sql.SetRecruitClaimMask(uid, mask)
}

func (s *MySQL) SetThreeTimes(uid int64, n int) error {
	if s.json != nil {
		return s.json.SetThreeTimes(uid, n)
	}
	return s.sql.SetThreeTimes(uid, n)
}

func (s *MySQL) SetTwoTimes(uid int64, n int) error {
	if s.json != nil {
		return s.json.SetTwoTimes(uid, n)
	}
	return s.sql.SetTwoTimes(uid, n)
}

func (s *MySQL) SetWornClothes(uid int64, clothes []WornCloth) error {
	if s.json != nil {
		return s.json.SetWornClothes(uid, clothes)
	}
	return s.sql.SetWornClothes(uid, clothes)
}

func (s *MySQL) TrySpendCoins(uid int64, amount int) (balance int, ok bool, err error) {
	if s.json != nil {
		return s.json.TrySpendCoins(uid, amount)
	}
	return s.sql.TrySpendCoins(uid, amount)
}

func (s *MySQL) TrySpendGold(uid int64, amount int) (balance int, ok bool, err error) {
	if s.json != nil {
		return s.json.TrySpendGold(uid, amount)
	}
	return s.sql.TrySpendGold(uid, amount)
}

func (s *MySQL) UpsertAchieveRule(uid int64, r AchieveRuleRow) error {
	if s.json != nil {
		return s.json.UpsertAchieveRule(uid, r)
	}
	return s.sql.UpsertAchieveRule(uid, r)
}

func (s *MySQL) UpsertNono(n *Nono) error {
	if s.json != nil {
		return s.json.UpsertNono(n)
	}
	return s.sql.UpsertNono(n)
}

func (s *MySQL) UpsertPet(p *Pet) error {
	if s.json != nil {
		return s.json.UpsertPet(p)
	}
	return s.sql.UpsertPet(p)
}

func (s *MySQL) UpsertSoulBead(uid int64, b SoulBead) error {
	if s.json != nil {
		return s.json.UpsertSoulBead(uid, b)
	}
	return s.sql.UpsertSoulBead(uid, b)
}

func (s *MySQL) UpsertTaskBuf(uid int64, taskID int, buf []byte) error {
	if s.json != nil {
		return s.json.UpsertTaskBuf(uid, taskID, buf)
	}
	return s.sql.UpsertTaskBuf(uid, taskID, buf)
}

func (s *MySQL) UpsertTaskStatus(uid int64, taskID, status int) error {
	if s.json != nil {
		return s.json.UpsertTaskStatus(uid, taskID, status)
	}
	return s.sql.UpsertTaskStatus(uid, taskID, status)
}

