package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	dir := filepath.Join("..", "internal", "store")
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	fset := token.NewFileSet()
	var methods []method
	entries, err := os.ReadDir(dir)
	if err != nil {
		panic(err)
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || name == "forward.go" || strings.HasSuffix(name, "_test.go") {
			continue
		}
		path := filepath.Join(dir, name)
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			fmt.Fprintf(os.Stderr, "parse %s: %v\n", name, err)
			continue
		}
		for _, d := range f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || fd.Name == nil || !fd.Name.IsExported() {
				continue
			}
			if len(fd.Recv.List) == 0 {
				continue
			}
			star, ok := fd.Recv.List[0].Type.(*ast.StarExpr)
			if !ok {
				continue
			}
			id, ok := star.X.(*ast.Ident)
			if !ok || id.Name != "sqlBackend" {
				continue
			}
			methods = append(methods, method{
				Name:    fd.Name.Name,
				Params:  fieldList(fd.Type.Params),
				Results: resultList(fd.Type.Results),
				Args:    argNames(fd.Type.Params),
			})
		}
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
	seen := map[string]bool{}
	var out strings.Builder
	out.WriteString("// Code generated by scripts/gen_store_forward.go; DO NOT EDIT.\n")
	out.WriteString("package store\n\n")
	out.WriteString("import \"database/sql\"\n\n")
	out.WriteString(`func (s *MySQL) Close() error {
	if s == nil {
		return nil
	}
	if s.json != nil {
		return s.json.Close()
	}
	if s.sql != nil {
		return s.sql.Close()
	}
	return nil
}

func (s *MySQL) Ping() error {
	if s == nil {
		return sql.ErrConnDone
	}
	if s.json != nil {
		return s.json.Ping()
	}
	if s.sql != nil {
		return s.sql.Ping()
	}
	return sql.ErrConnDone
}

func (s *MySQL) DB() *sql.DB {
	if s == nil || s.sql == nil {
		return nil
	}
	return s.sql.DB()
}

`)
	for _, m := range methods {
		if m.Name == "Close" || m.Name == "Ping" || m.Name == "DB" || seen[m.Name] {
			continue
		}
		seen[m.Name] = true
		sig := "func (s *MySQL) " + m.Name + "(" + m.Params + ")"
		if m.Results != "" {
			sig += " " + m.Results
		}
		out.WriteString(sig + " {\n")
		out.WriteString("\tif s.json != nil {\n")
		out.WriteString("\t\treturn s.json." + m.Name + "(" + m.Args + ")\n")
		out.WriteString("\t}\n")
		out.WriteString("\treturn s.sql." + m.Name + "(" + m.Args + ")\n")
		out.WriteString("}\n\n")
	}
	outPath := filepath.Join(dir, "forward.go")
	if err := os.WriteFile(outPath, []byte(out.String()), 0644); err != nil {
		panic(err)
	}
	fmt.Println("wrote", len(seen), "forwarders to", outPath)
}

type method struct {
	Name, Params, Results, Args string
}

func fieldList(fl *ast.FieldList) string {
	if fl == nil {
		return ""
	}
	var parts []string
	for _, f := range fl.List {
		typ := exprString(f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, typ)
			continue
		}
		names := make([]string, len(f.Names))
		for i, n := range f.Names {
			names[i] = n.Name
		}
		parts = append(parts, strings.Join(names, ", ")+" "+typ)
	}
	return strings.Join(parts, ", ")
}

func resultList(fl *ast.FieldList) string {
	if fl == nil || len(fl.List) == 0 {
		return ""
	}
	inner := fieldList(fl)
	if len(fl.List) == 1 && len(fl.List[0].Names) == 0 {
		return inner
	}
	return "(" + inner + ")"
}

func argNames(fl *ast.FieldList) string {
	if fl == nil {
		return ""
	}
	var names []string
	for _, f := range fl.List {
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
	}
	return strings.Join(names, ", ")
}

func exprString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + exprString(t.Elt)
		}
		return "[" + exprString(t.Len) + "]" + exprString(t.Elt)
	case *ast.Ellipsis:
		return "..." + exprString(t.Elt)
	case *ast.InterfaceType:
		return "any"
	case *ast.MapType:
		return "map[" + exprString(t.Key) + "]" + exprString(t.Value)
	case *ast.BasicLit:
		return t.Value
	default:
		return fmt.Sprintf("%T", e)
	}
}
