-- 尼尔号私服增量存档 Schema
-- 库名：niao；账号默认 root/root

CREATE DATABASE IF NOT EXISTS niao CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE niao;

-- 1. 用户表
CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT PRIMARY KEY,
  email VARCHAR(128) NOT NULL UNIQUE,
  password VARCHAR(128) NOT NULL,
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  color INT NOT NULL DEFAULT 0,
  role_created TINYINT NOT NULL DEFAULT 0,
  coins INT NOT NULL DEFAULT 0 COMMENT '赛尔豆',
  gold INT NOT NULL DEFAULT 0 COMMENT '金豆余额（与 gold_ledger 对账）',
  energy INT NOT NULL DEFAULT 100,
  exp_total BIGINT NOT NULL DEFAULT 0 COMMENT '角色侧经验汇总',
  map_id INT NOT NULL DEFAULT 1,
  pos_x INT NOT NULL DEFAULT 300,
  pos_y INT NOT NULL DEFAULT 270,
  current_server INT NOT NULL DEFAULT 0,
  session_hex VARCHAR(64) NOT NULL DEFAULT '',
  last_online BIGINT NOT NULL DEFAULT 0,
  login_cnt INT NOT NULL DEFAULT 0,
  login_streak INT NOT NULL DEFAULT 0,
  register_time BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_nickname (nickname),
  INDEX idx_last_online (last_online)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pets (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  catch_time BIGINT NOT NULL,
  pet_id INT NOT NULL,
  pet_name VARCHAR(64) NOT NULL DEFAULT '',
  level INT NOT NULL DEFAULT 1,
  exp INT NOT NULL DEFAULT 0,
  dv INT NOT NULL DEFAULT 0,
  nature INT NOT NULL DEFAULT 0,
  bag_pos INT NOT NULL DEFAULT -1,
  in_bag TINYINT NOT NULL DEFAULT 1,
  skills_json JSON NOT NULL,
  extra_json JSON NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_catch (user_id, catch_time),
  INDEX idx_user_pet (user_id, pet_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_tasks (
  user_id BIGINT NOT NULL,
  task_id INT NOT NULL,
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0未接 1已接 3完成',
  buf_blob VARBINARY(20) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, task_id),
  INDEX idx_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS items (
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  expire_time INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS props (
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  expire_time INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exp_ledger (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  pet_row_id BIGINT NOT NULL DEFAULT 0,
  delta INT NOT NULL,
  level_after INT NOT NULL DEFAULT 0,
  exp_after INT NOT NULL DEFAULT 0,
  reason VARCHAR(64) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_time (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gold_ledger (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  delta INT NOT NULL,
  balance_after INT NOT NULL,
  reason VARCHAR(64) NOT NULL DEFAULT '',
  ref_id VARCHAR(64) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_time (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS equips (
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  count INT NOT NULL DEFAULT 1,
  enhance_lv INT NOT NULL DEFAULT 0,
  equipped_slot INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS soul_beads (
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  hatch_progress INT NOT NULL DEFAULT 0,
  extra_json JSON NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS essences (
  user_id BIGINT NOT NULL,
  item_id INT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  breed_mon_id INT NOT NULL DEFAULT 0,
  breed_time INT NOT NULL DEFAULT 0,
  hatch_start BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gm_audit (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  admin VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  target_user BIGINT NOT NULL DEFAULT 0,
  detail_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_time (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_friends (
  user_id BIGINT NOT NULL,
  friend_id BIGINT NOT NULL,
  time_poke INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, friend_id),
  INDEX idx_friend (friend_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_blacklist (
  user_id BIGINT NOT NULL,
  black_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, black_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_worn_clothes (
  user_id BIGINT NOT NULL,
  slot_idx INT NOT NULL,
  item_id INT NOT NULL,
  level INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, slot_idx)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_mails (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  template INT NOT NULL DEFAULT 0,
  mail_time BIGINT NOT NULL DEFAULT 0,
  from_id BIGINT NOT NULL DEFAULT 0,
  from_nick VARCHAR(16) NOT NULL DEFAULT '',
  content TEXT NOT NULL,
  is_read TINYINT NOT NULL DEFAULT 0,
  is_claimed TINYINT NOT NULL DEFAULT 0,
  reward_json TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_time (user_id, mail_time DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_progress (
  user_id BIGINT NOT NULL PRIMARY KEY,
  brave_cur INT NOT NULL DEFAULT 1,
  brave_max INT NOT NULL DEFAULT 1,
  fresh_cur INT NOT NULL DEFAULT 1,
  fresh_max INT NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_spt_defeated (
  user_id BIGINT NOT NULL,
  boss_key INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, boss_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_nono (
  user_id BIGINT NOT NULL PRIMARY KEY,
  has_nono TINYINT NOT NULL DEFAULT 0,
  flag INT NOT NULL DEFAULT 1,
  state INT NOT NULL DEFAULT 0,
  nick VARCHAR(16) NOT NULL DEFAULT 'NoNo',
  color INT NOT NULL DEFAULT 16777215,
  super_nono INT NOT NULL DEFAULT 0,
  power INT NOT NULL DEFAULT 100,
  mate INT NOT NULL DEFAULT 100,
  iq INT NOT NULL DEFAULT 0,
  ai SMALLINT NOT NULL DEFAULT 0,
  birth BIGINT NOT NULL DEFAULT 0,
  charge_time INT NOT NULL DEFAULT 0,
  func_bits VARBINARY(20) NOT NULL DEFAULT '',
  super_energy INT NOT NULL DEFAULT 0,
  super_level INT NOT NULL DEFAULT 0,
  super_stage INT NOT NULL DEFAULT 0,
  super_months INT NOT NULL DEFAULT 0,
  vip_value INT NOT NULL DEFAULT 0,
  auto_charge INT NOT NULL DEFAULT 0,
  vip_end_time BIGINT NOT NULL DEFAULT 0,
  open_gold_charged TINYINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_fitments (
  user_id BIGINT NOT NULL,
  slot INT NOT NULL,
  item_id INT NOT NULL,
  pos_x INT NOT NULL DEFAULT 0,
  pos_y INT NOT NULL DEFAULT 0,
  dir INT NOT NULL DEFAULT 0,
  status INT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, slot),
  INDEX idx_fitment_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_breed (
  user_id BIGINT NOT NULL PRIMARY KEY,
  state_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
